// Dictionary of difficult words found in the 16PF questions, with short definitions.
export const GLOSSARY: Record<string, string> = {
  semiclassical: "Music blending classical and popular styles.",
  sarcastic: "Using sharp irony or mockery to criticize someone.",
  conceited: "Excessively proud of oneself; vain.",
  propaganda: "Biased information used to promote a viewpoint or cause.",
  plodding: "Slow, steady, and unimaginative in approach.",
  probation: "A supervised testing period, often as an alternative to prison.",
  parole: "Early supervised release from prison before a sentence ends.",
  diplomacy: "The skill of handling situations tactfully and sensitively.",
  turmoil: "A state of great confusion or disorder.",
  dejected: "Feeling sad and disheartened; dispirited.",
  gusto: "Great enthusiasm and energy; hearty enjoyment.",
  unconventional: "Not following accepted norms; unusual or untraditional.",
  pomp: "Elaborate and ceremonial display; grandeur.",
  splendor: "Grand, impressive beauty and brilliance.",
  conscientious: "Careful, thorough, and morally guided.",
  exacting: "Demanding great precision, effort, or accuracy.",
  idealists: "People who pursue high principles and noble goals.",
  foolhardy: "Recklessly bold without regard for danger.",
  profound: "Having deep meaning or great insight.",
  expedient: "Convenient and practical, sometimes ignoring ethics.",
  deferential: "Respectfully yielding to another's judgment or wishes.",
  forthright: "Direct and outspoken; straight to the point.",
  utilitarian: "Focused on practical usefulness rather than beauty.",
  boisterous: "Loud, energetic, and cheerfully rough.",
  discreet: "Careful not to cause embarrassment or attract attention.",
  impulsive: "Acting on sudden feeling without careful thought.",
  sarcasm: "The use of irony to mock or convey contempt.",
  astute: "Having a clever, sharp ability to notice and understand things.",
  prudent: "Acting with care and thought for the future.",
  tenacious: "Holding firmly to a purpose; persistent.",
  spontaneous: "Acting naturally without planning or external pressure.",
  introspective: "Examining one's own thoughts and feelings.",
  apprehensive: "Anxious or fearful about the future.",
  gregarious: "Enjoying the company of others; sociable.",
};
