export interface Question {
  id: number;
  text: string;
  options: [string, string, string];
  factor?: string; // which of the 16 factors this contributes to
}

export interface Factor {
  id: string;
  label: string;
  lowPole: string;
  highPole: string;
  description: string;
  color: string;
}

export const FACTORS: Factor[] = [
  { id: "A", label: "Warmth", lowPole: "Reserved", highPole: "Warm", description: "Relates to how much you enjoy and seek closeness with others.", color: "#e07070" },
  { id: "B", label: "Reasoning", lowPole: "Concrete", highPole: "Abstract", description: "Reflects your ability to solve abstract problems and think analytically.", color: "#f59e0b" },
  { id: "C", label: "Emotional Stability", lowPole: "Reactive", highPole: "Stable", description: "Indicates how well you manage emotions and handle stress.", color: "#84a98c" },
  { id: "E", label: "Dominance", lowPole: "Deferential", highPole: "Dominant", description: "Reflects your assertiveness and tendency to influence others.", color: "#7c6fcd" },
  { id: "F", label: "Liveliness", lowPole: "Serious", highPole: "Lively", description: "Captures spontaneity, enthusiasm, and energy in daily life.", color: "#f59e0b" },
  { id: "G", label: "Rule-Consciousness", lowPole: "Expedient", highPole: "Rule-Conscious", description: "Reflects how strongly you follow rules and moral standards.", color: "#2e4d77" },
  { id: "H", label: "Social Boldness", lowPole: "Shy", highPole: "Bold", description: "Measures comfort in social situations and willingness to take social risks.", color: "#e07070" },
  { id: "I", label: "Sensitivity", lowPole: "Utilitarian", highPole: "Sensitive", description: "Reflects emotional depth, aesthetic sensitivity, and empathy.", color: "#84a98c" },
  { id: "L", label: "Vigilance", lowPole: "Trusting", highPole: "Vigilant", description: "Indicates level of suspicion vs. trust toward others' motives.", color: "#7c6fcd" },
  { id: "M", label: "Abstractedness", lowPole: "Grounded", highPole: "Abstracted", description: "Reflects tendency toward imagination and inner mental life.", color: "#f59e0b" },
  { id: "N", label: "Privateness", lowPole: "Forthright", highPole: "Private", description: "Measures how guarded or open you are about yourself.", color: "#2e4d77" },
  { id: "O", label: "Apprehension", lowPole: "Self-Assured", highPole: "Apprehensive", description: "Reflects worry, self-doubt, and feelings of guilt.", color: "#e07070" },
  { id: "Q1", label: "Openness to Change", lowPole: "Traditional", highPole: "Open", description: "Measures receptivity to new ideas and willingness to change.", color: "#84a98c" },
  { id: "Q2", label: "Self-Reliance", lowPole: "Group-Oriented", highPole: "Self-Reliant", description: "Reflects preference for working alone vs. with others.", color: "#7c6fcd" },
  { id: "Q3", label: "Perfectionism", lowPole: "Flexible", highPole: "Perfectionist", description: "Captures self-discipline, precision, and drive to do things correctly.", color: "#f59e0b" },
  { id: "Q4", label: "Tension", lowPole: "Relaxed", highPole: "Tense", description: "Measures the level of driven, frustrated tension and anxiety.", color: "#e07070" },
];

// Simplified scoring map: question id -> { factor, scoring }
// scoring: 'a'=2, 'b'=1, 'c'=0 OR reversed
// This is a simplified approximation for educational/demo purposes
export const SCORING_MAP: Record<number, { factor: string; reverse: boolean }> = {
  3: { factor: "A", reverse: true },
  10: { factor: "A", reverse: false },
  36: { factor: "A", reverse: false },
  83: { factor: "A", reverse: false },
  107: { factor: "A", reverse: true },
  135: { factor: "A", reverse: false },
  158: { factor: "A", reverse: true },

  28: { factor: "B", reverse: false },
  53: { factor: "B", reverse: false },
  54: { factor: "B", reverse: false },
  77: { factor: "B", reverse: false },
  78: { factor: "B", reverse: false },
  102: { factor: "B", reverse: false },
  103: { factor: "B", reverse: false },
  127: { factor: "B", reverse: false },
  128: { factor: "B", reverse: false },
  152: { factor: "B", reverse: false },
  153: { factor: "B", reverse: false },
  163: { factor: "B", reverse: false },
  177: { factor: "B", reverse: false },
  178: { factor: "B", reverse: false },

  4: { factor: "C", reverse: false },
  18: { factor: "C", reverse: true },
  29: { factor: "C", reverse: true },
  49: { factor: "C", reverse: true },
  73: { factor: "C", reverse: false },
  99: { factor: "C", reverse: true },
  118: { factor: "C", reverse: true },
  129: { factor: "C", reverse: true },
  149: { factor: "C", reverse: true },

  38: { factor: "E", reverse: false },
  56: { factor: "E", reverse: false },
  70: { factor: "E", reverse: false },
  88: { factor: "E", reverse: false },
  92: { factor: "E", reverse: false },
  113: { factor: "E", reverse: false },

  7: { factor: "F", reverse: true },
  33: { factor: "F", reverse: false },
  69: { factor: "F", reverse: false },
  114: { factor: "F", reverse: false },
  131: { factor: "F", reverse: false },
  182: { factor: "F", reverse: false },

  6: { factor: "G", reverse: false },
  42: { factor: "G", reverse: false },
  48: { factor: "G", reverse: false },
  98: { factor: "G", reverse: false },
  160: { factor: "G", reverse: false },
  184: { factor: "G", reverse: false },

  35: { factor: "H", reverse: true },
  61: { factor: "H", reverse: true },
  85: { factor: "H", reverse: true },
  94: { factor: "H", reverse: true },
  106: { factor: "H", reverse: false },
  110: { factor: "H", reverse: false },

  12: { factor: "I", reverse: false },
  37: { factor: "I", reverse: false },
  87: { factor: "I", reverse: true },
  115: { factor: "I", reverse: false },
  137: { factor: "I", reverse: true },
  138: { factor: "I", reverse: false },

  14: { factor: "L", reverse: false },
  46: { factor: "L", reverse: false },
  50: { factor: "L", reverse: false },
  79: { factor: "L", reverse: false },
  80: { factor: "L", reverse: false },

  11: { factor: "M", reverse: false },
  29: { factor: "M", reverse: false },
  62: { factor: "M", reverse: true },
  87: { factor: "M", reverse: false },
  109: { factor: "M", reverse: false },

  17: { factor: "N", reverse: true },
  57: { factor: "N", reverse: false },
  60: { factor: "N", reverse: false },
  72: { factor: "N", reverse: false },
  136: { factor: "N", reverse: true },

  19: { factor: "O", reverse: false },
  43: { factor: "O", reverse: false },
  44: { factor: "O", reverse: false },
  74: { factor: "O", reverse: false },
  93: { factor: "O", reverse: false },
  118: { factor: "O", reverse: false },
  123: { factor: "O", reverse: false },

  31: { factor: "Q1", reverse: false },
  59: { factor: "Q1", reverse: false },
  120: { factor: "Q1", reverse: true },
  148: { factor: "Q1", reverse: true },
  169: { factor: "Q1", reverse: false },
  172: { factor: "Q1", reverse: false },

  71: { factor: "Q2", reverse: false },
  82: { factor: "Q2", reverse: false },
  86: { factor: "Q2", reverse: false },
  122: { factor: "Q2", reverse: true },
  146: { factor: "Q2", reverse: false },
  158: { factor: "Q2", reverse: false },

  30: { factor: "Q3", reverse: false },
  48: { factor: "Q3", reverse: false },
  75: { factor: "Q3", reverse: false },
  125: { factor: "Q3", reverse: false },
  134: { factor: "Q3", reverse: false },
  184: { factor: "Q3", reverse: false },

  5: { factor: "Q4", reverse: false },
  25: { factor: "Q4", reverse: true },
  41: { factor: "Q4", reverse: false },
  99: { factor: "Q4", reverse: false },
  124: { factor: "Q4", reverse: false },
  147: { factor: "Q4", reverse: false },
  149: { factor: "Q4", reverse: false },
  174: { factor: "Q4", reverse: false },
};

export const QUESTIONS: Question[] = [
  {id:1,text:"I have the instructions for this test clear in mind.",options:["yes","uncertain","no"]},
  {id:2,text:"I am ready to answer each question as truthfully as possible.",options:["yes","uncertain","no"]},
  {id:3,text:"I would rather have a house:",options:["in a sociable suburb","in between","alone in the deep woods"]},
  {id:4,text:"I can find enough energy to face my difficulties.",options:["always","generally","seldom"]},
  {id:5,text:"I feel a bit nervous of wild animals even when they are in strong cages.",options:["yes (true)","uncertain","no (false)"]},
  {id:6,text:"I hold back from criticizing people and their ideas.",options:["yes","sometimes","no"]},
  {id:7,text:"I make smart, sarcastic remarks to people if I think they deserve it.",options:["generally","sometimes","never"]},
  {id:8,text:"I prefer semiclassical music to popular tunes.",options:["true","uncertain","false"]},
  {id:9,text:"If I saw two neighbors' children fighting, I would:",options:["leave them to settle it","uncertain","reason with them"]},
  {id:10,text:"On social occasions I:",options:["readily come forward","in between","prefer to stay quietly in the background"]},
  {id:11,text:"It would be more interesting to be:",options:["a construction engineer","uncertain","a writer of plays"]},
  {id:12,text:"I would rather stop in the street to watch an artist painting than listen to some people having a quarrel.",options:["true","uncertain","false"]},
  {id:13,text:"I can generally put up with conceited people, even though they brag or show they think too well of themselves.",options:["yes","in between","no"]},
  {id:14,text:"You can almost always notice on a man's face when he is dishonest.",options:["yes","in between","no"]},
  {id:15,text:"It would be good for everyone if vacations (holidays) were longer and everyone had to take them.",options:["agree","uncertain","disagree"]},
  {id:16,text:"I would rather take the gamble of a job with possibly large but uneven earnings, than one with a steady, small salary.",options:["yes","uncertain","no"]},
  {id:17,text:"I talk about my feelings:",options:["only if necessary","in between","readily, whenever I have a chance"]},
  {id:18,text:"Once in a while I have a sense of vague danger or sudden dread for reasons that I do not understand.",options:["yes","in between","no"]},
  {id:19,text:"When criticized wrongly for something I did not do, I:",options:["have no feeling of guilt","in between","still feel a bit guilty"]},
  {id:20,text:"Money can buy almost everything.",options:["yes","uncertain","no"]},
  {id:21,text:"My decisions are governed more by my:",options:["heart","feelings and reason equally","head"]},
  {id:22,text:"Most people would be happier if they lived more with their fellows and did the same things as others.",options:["yes","in between","no"]},
  {id:23,text:"I occasionally get puzzled, when looking in a mirror, as to which is my right and left.",options:["true","uncertain","false"]},
  {id:24,text:"When talking, I like:",options:["to say things, just as they occur to me","in between","to get my thoughts well organized first"]},
  {id:25,text:"When something really makes me furious, I find I calm down again quite quickly.",options:["yes","in between","no"]},
  {id:26,text:"With the same hours and pay, it would be more interesting to be:",options:["a carpenter or cook","uncertain","a waiter in a good restaurant"]},
  {id:27,text:"I have been elected to:",options:["only a few offices","several","many offices"]},
  {id:28,text:'"Spade" is to "dig" as "knife" is to:',options:["sharp","cut","point"]},
  {id:29,text:"I sometimes can't get to sleep because an idea keeps running through my mind.",options:["true","uncertain","false"]},
  {id:30,text:"In my personal life I reach the goals I set, almost all the time.",options:["true","uncertain","false"]},
  {id:31,text:"An out-dated law should be changed:",options:["only after considerable discussion","in between","promptly"]},
  {id:32,text:"I am uncomfortable when I work on a project requiring quick action affecting others.",options:["true","in between","false"]},
  {id:33,text:"Most of the people I know would rate me as an amusing talker.",options:["yes","uncertain","no"]},
  {id:34,text:'When I see "sloppy," untidy people, I:',options:["just accept it","in between","get disgusted and annoyed"]},
  {id:35,text:"I get slightly embarrassed if I suddenly become the focus of attention in a social group.",options:["yes","in between","no"]},
  {id:36,text:"I am always glad to join a large gathering, for example, a party, dance, or public meeting.",options:["yes","in between","no"]},
  {id:37,text:"In school I preferred (or prefer):",options:["music","uncertain","handwork and crafts"]},
  {id:38,text:"When I have been put in charge of something, I insist that my instructions are followed or else I resign.",options:["yes","sometimes","no"]},
  {id:39,text:"For parents, it is more important to:",options:["help their children develop their affections","in between","teach their children how to control emotions"]},
  {id:40,text:"In a group task I would rather:",options:["try to improve arrangements","in between","keep the records and see that rules are followed"]},
  {id:41,text:"I feel a need every now and then to engage in a tough physical activity.",options:["yes","in between","no"]},
  {id:42,text:"I would rather mix with polite people than rough, rebellious individuals.",options:["yes","in between","no"]},
  {id:43,text:"I feel terribly dejected when people criticize me in a group.",options:["true","in between","false"]},
  {id:44,text:"If I am called in by my boss, I:",options:["make it a chance to ask for something I want","in between","fear I've done something wrong"]},
  {id:45,text:'What this world needs is:',options:['more steady and "solid" citizens',"uncertain",'more "idealists" with plans for a better world']},
  {id:46,text:"I am always keenly aware of attempts at propaganda in things I read.",options:["yes","uncertain","no"]},
  {id:47,text:"As a teenager, I joined in school sports:",options:["occasionally","fairly often","a great deal"]},
  {id:48,text:"I keep my room well organized, with things in known places almost all the time.",options:["yes","in between","no"]},
  {id:49,text:"I sometimes get in a state of tension and turmoil as I think of the day's happenings.",options:["yes","in between","no"]},
  {id:50,text:"I sometimes doubt whether people I am talking to are really interested in what I am saying.",options:["yes","in between","no"]},
  {id:51,text:"If I chose, I would rather be:",options:["a forester","uncertain","a high school teacher"]},
  {id:52,text:"For special holidays and birthdays, I:",options:["like to give personal presents","uncertain","feel that buying presents is a bit of a nuisance"]},
  {id:53,text:'"Tired" is to "work" as "proud" is to:',options:["smile","success","happy"]},
  {id:54,text:"Which of the following items is different in kind from the others?",options:["candle","moon","electric light"]},
  {id:55,text:"I have been let down by my friends:",options:["hardly ever","occasionally","quite a lot"]},
  {id:56,text:"I have some characteristics in which I feel definitely superior to most people.",options:["yes","uncertain","no"]},
  {id:57,text:"When I get upset, I try hard to hide my feelings from others.",options:["true","in between","false"]},
  {id:58,text:"I like to go out to a show or entertainment:",options:["more than once a week (more than average)","about once a week (average)","less than once a week (less than average)"]},
  {id:59,text:"I think that plenty of freedom is more important than good manners and respect for the law.",options:["true","uncertain","false"]},
  {id:60,text:"I tend to keep quiet in the presence of senior persons (people of greater experience, age, or rank).",options:["yes","in between","no"]},
  {id:61,text:"I find it hard to address or recite to a large group.",options:["yes","in between","no"]},
  {id:62,text:"I have a good sense of direction (find it easy to tell which is North, South, East, or West) when in a strange place.",options:["yes","in between","no"]},
  {id:63,text:"If someone got mad at me, I would:",options:["try to calm him down","uncertain","get irritated"]},
  {id:64,text:'When I read an unfair magazine article, I am more inclined to forget it than to feel like "hitting back."',options:["true","uncertain","false"]},
  {id:65,text:"My memory tends to drop a lot of unimportant, trivial things, for example, names of streets or stores in town.",options:["yes","in between","no"]},
  {id:66,text:"I could enjoy the life of an animal doctor, handling disease and surgery of animals.",options:["yes","in between","no"]},
  {id:67,text:"I eat my food with gusto, not always so carefully and properly as some people.",options:["true","uncertain","false"]},
  {id:68,text:"There are times when I don't feel in the right mood to see anyone.",options:["very rarely","in between","quite often"]},
  {id:69,text:"People sometimes warn me that I show excitement in voice and manner too obviously.",options:["yes","in between","no"]},
  {id:70,text:"As a teenager, if I differed in opinion from my parents, I usually:",options:["kept my own opinion","in between","accepted their authority"]},
  {id:71,text:"I would prefer to have an office of my own, not sharing it with another person.",options:["yes","uncertain","no"]},
  {id:72,text:"I would rather enjoy life quietly in my own way than be admired for my achievements.",options:["true","uncertain","false"]},
  {id:73,text:"I feel mature in most things.",options:["true","uncertain","false"]},
  {id:74,text:"I find myself upset rather than helped by the kind of criticism that many people offer one.",options:["often","occasionally","never"]},
  {id:75,text:"I am always able to keep the expression of my feelings under exact control.",options:["yes","in between","no"]},
  {id:76,text:"In making a useful invention, I would prefer:",options:["working on it in the laboratory","uncertain","selling it to people"]},
  {id:77,text:'"Surprise" is to "strange" as "fear" is to:',options:["brave","anxious","terrible"]},
  {id:78,text:"Which of the following fractions is not in the same class as the others?",options:["3/7","3/9","3/11"]},
  {id:79,text:"Some people seem to ignore or avoid me, although I don't know why.",options:["true","uncertain","false"]},
  {id:80,text:"People treat me less reasonably than my good intentions deserve.",options:["often","occasionally","never"]},
  {id:81,text:"The use of foul language, even when it is not in a mixed group of men and women, still disgusts me.",options:["yes","in between","no"]},
  {id:82,text:"I have decidedly fewer friends than most people.",options:["yes","in between","no"]},
  {id:83,text:"I would hate to be where there wouldn't be a lot of people to talk to.",options:["true","uncertain","false"]},
  {id:84,text:"People sometimes call me careless, even though they think I'm a likable person.",options:["yes","in between","no"]},
  {id:85,text:'"Stage-fright" in various social situations is something I have experienced:',options:["quite often","occasionally","hardly ever"]},
  {id:86,text:"When I am in a small group, I am content to sit back and let others do most of the talking.",options:["yes","in between","no"]},
  {id:87,text:"I prefer reading:",options:["a realistic account of military or political battles","uncertain","a sensitive, imaginative novel"]},
  {id:88,text:'When bossy people try to "push me around," I do just the opposite of what they wish.',options:["yes","in between","no"]},
  {id:89,text:"Business superiors or members of my family, as a rule, find fault with me only when there is real cause.",options:["true","in between","false"]},
  {id:90,text:"In streets or stores, I dislike the way some persons stare at people.",options:["yes","in between","no"]},
  {id:91,text:"On a long journey, I would prefer to:",options:["read something profound, but interesting","uncertain","pass the time talking casually with a fellow passenger"]},
  {id:92,text:"In a situation which may become dangerous, I believe in making a fuss and speaking up even if calmness and politeness are lost.",options:["yes","in between","no"]},
  {id:93,text:"If acquaintances treat me badly and show they dislike me:",options:["it doesn't upset me a bit","in between","I tend to get downhearted"]},
  {id:94,text:"I find it embarrassing to have praise or compliments bestowed on me.",options:["yes","in between","no"]},
  {id:95,text:"I would rather have a job with:",options:["a fixed, certain salary","in between","a larger salary, which depended on my constantly persuading people I am worth it"]},
  {id:96,text:"To keep informed, I like:",options:["to discuss issues with people","in between","to rely on the actual news reports"]},
  {id:97,text:"I like to take an active part in social affairs, committee work, etc.",options:["yes","in between","no"]},
  {id:98,text:"In carrying out a task, I am not satisfied unless even the minor details are given close attention.",options:["yes","in between","false"]},
  {id:99,text:"Quite small setbacks occasionally irritate me too much.",options:["yes","in between","no"]},
  {id:100,text:"I am always a sound sleeper, never walking or talking in my sleep.",options:["yes","in between","no"]},
  {id:101,text:"It would be more interesting to work in a business:",options:["talking to customers","in between","keeping office accounts and records"]},
  {id:102,text:'"Size" is to "length" as "dishonest" is to:',options:["prison","sin","stealing"]},
  {id:103,text:"AB is to dc as SR is to:",options:["qp","pq","tu"]},
  {id:104,text:"When people are unreasonable, I just:",options:["keep quiet","uncertain","despise them"]},
  {id:105,text:"If people talk loudly while I am listening to music, I:",options:["can keep my mind on the music and not be bothered","in between","find it spoils my enjoyment and annoys me"]},
  {id:106,text:"I think I am better described as:",options:["polite and quiet","in between","forceful"]},
  {id:107,text:"I attend social functions only when I have to, and stay away any other time.",options:["yes","uncertain","no"]},
  {id:108,text:"To be cautious and expect little is better than to be happy at heart, always expecting success.",options:["true","uncertain","false"]},
  {id:109,text:"In thinking of difficulties in my work, I:",options:["try to plan ahead, before I meet them","in between","assume I can handle them when they come"]},
  {id:110,text:"I find it easy to mingle among people at a social gathering.",options:["true","uncertain","false"]},
  {id:111,text:"When a bit of diplomacy and persuasion are needed to get people moving, I am generally the one asked to do it.",options:["yes","in between","no"]},
  {id:112,text:"It would be more interesting to be:",options:["a guidance worker helping young people find jobs","uncertain","a manager in efficiency engineering"]},
  {id:113,text:"If I am quite sure that a person is unjust or behaving selfishly, I show him up, even if it takes some trouble.",options:["yes","in between","no"]},
  {id:114,text:"I sometimes make foolish remarks in fun, just to surprise people and see what they will say.",options:["yes","in between","no"]},
  {id:115,text:"I would enjoy being a newspaper writer on drama, concerts, opera, etc.",options:["yes","uncertain","no"]},
  {id:116,text:"I never feel the urge to doodle and fidget when kept sitting still at a meeting.",options:["true","uncertain","false"]},
  {id:117,text:"If someone tells me something which I know is wrong, I am more likely to say to myself:",options:['"He is a liar"',"in between",'"Apparently he is misinformed"']},
  {id:118,text:"I feel some punishment is coming to me even when I have done nothing wrong.",options:["often","occasionally","never"]},
  {id:119,text:"The idea that sickness comes as much from mental as physical causes is much exaggerated.",options:["yes","in between","no"]},
  {id:120,text:"The pomp and splendor of any big state ceremony are things which should be preserved.",options:["yes","in between","no"]},
  {id:121,text:"It bothers me if people think I am being too unconventional or odd.",options:["a lot","somewhat","not at all"]},
  {id:122,text:"In constructing something I would rather work:",options:["with a committee","uncertain","on my own"]},
  {id:123,text:"I have periods when it's hard to stop a mood of self-pity.",options:["often","occasionally","never"]},
  {id:124,text:"Often I get angry with people too quickly.",options:["yes","in between","no"]},
  {id:125,text:"I can always change old habits without difficulty and without slipping back.",options:["yes","in between","no"]},
  {id:126,text:"If I could, I would rather be:",options:["a lawyer","uncertain","a navigator or pilot"]},
  {id:127,text:'"Better" is to "worst" as "slower" is to:',options:["fast","best","quickest"]},
  {id:128,text:"Which of the following should come next at the end of this row of letters: x0000XX000XXx?",options:["0XXX","00XX","X000"]},
  {id:129,text:"When the time comes for something I have planned and looked forward to, I occasionally do not feel up to going.",options:["true","in between","false"]},
  {id:130,text:"I can work carefully on most things without being bothered by people making a lot of noise around me.",options:["yes","in between","no"]},
  {id:131,text:"I occasionally tell strangers things that seem to me important, regardless of whether they ask about them.",options:["yes","in between","no"]},
  {id:132,text:"I spend much of my spare time talking with friends about social events enjoyed in the past.",options:["yes","in between","no"]},
  {id:133,text:'I enjoy doing "daring," foolhardy things "just for fun."',options:["yes","in between","no"]},
  {id:134,text:"I find the sight of an untidy room very annoying.",options:["yes","in between","no"]},
  {id:135,text:"I consider myself a very sociable, outgoing person.",options:["yes","in between","no"]},
  {id:136,text:"In social contacts I:",options:["show my emotions as I wish","in between","keep my emotions to myself"]},
  {id:137,text:"I enjoy music that is:",options:["light, dry, and brisk","in between","emotional and sentimental"]},
  {id:138,text:"I admire the beauty of a poem more than that of a well-made gun.",options:["yes","uncertain","no"]},
  {id:139,text:"If a good remark of mine is passed by, I:",options:["let it go","in between","give people a chance to hear it again"]},
  {id:140,text:"I would like to work as a probation officer with criminals on parole.",options:["yes","in between","no"]},
  {id:141,text:"One should be careful about mixing with all kinds of strangers, since there are dangers of infection and so on.",options:["yes","uncertain","no"]},
  {id:142,text:"In traveling abroad, I would rather go on an expertly conducted tour than plan by myself the places I wish to visit.",options:["yes","uncertain","no"]},
  {id:143,text:"I am properly regarded as only a plodding, half-successful person.",options:["yes","uncertain","no"]},
  {id:144,text:"If people take advantage of my friendliness, I do not resent it and I soon forget.",options:["true","uncertain","false"]},
  {id:145,text:"If a heated argument developed between other members taking part in a group discussion, I would:",options:['like to see a "winner"',"in between","wish that it would be smoothed over"]},
  {id:146,text:"I like to do my planning alone, without interruptions and suggestions from others.",options:["yes","in between","no"]},
  {id:147,text:"I sometimes let my actions get swayed by feelings of jealousy.",options:["yes","in between","no"]},
  {id:148,text:'I believe firmly "the boss may not always be right, but he always has the right to be boss."',options:["yes","uncertain","no"]},
  {id:149,text:"I get tense as I think of all the things lying ahead of me.",options:["yes","sometimes","no"]},
  {id:150,text:"If people shout suggestions when I'm playing a game, it doesn't upset me.",options:["true","uncertain","false"]},
  {id:151,text:"It would be more interesting to be:",options:["an artist","uncertain","a secretary running a club"]},
  {id:152,text:"Which of the following words does not properly belong with the others?",options:["any","some","most"]},
  {id:153,text:'"Flame" is to "heat" as "rose" is to:',options:["thorn","red petals","scent"]},
  {id:154,text:"I have vivid dreams, disturbing my sleep.",options:["often","occasionally","practically never"]},
  {id:155,text:"If the odds are really against something's being a success, I still believe in taking the risk.",options:["yes","in between","no"]},
  {id:156,text:"I like it when I know so well what the group has to do that I naturally become the one in command.",options:["yes","in between","no"]},
  {id:157,text:"I would rather dress with quiet correctness than with eye-catching personal style.",options:["true","uncertain","false"]},
  {id:158,text:"An evening with a quiet hobby appeals to me more than a lively party.",options:["true","uncertain","false"]},
  {id:159,text:"I close my mind to well-meant suggestions of others, even though I know I shouldn't.",options:["occasionally","hardly ever","never"]},
  {id:160,text:"I always make it a point, in deciding anything, to refer to basic rules of right and wrong.",options:["yes","in between","no"]},
  {id:161,text:"I somewhat dislike having a group watch me at work.",options:["yes","in between","no"]},
  {id:162,text:"Because it is not always possible to get things done by gradual, reasonable methods, it is sometimes necessary to use force.",options:["true","in between","false"]},
  {id:163,text:"In school I preferred (or prefer):",options:["English","uncertain","mathematics or arithmetic"]},
  {id:164,text:"I have sometimes been troubled by people's saying bad things about me, behind my back, with no grounds at all.",options:["yes","uncertain","no"]},
  {id:165,text:"Talk with ordinary, habit-bound, conventional people:",options:["is often quite interesting and has a lot to it","in between","annoys me because it deals with trifles and lacks depth"]},
  {id:166,text:"Some things make me so angry that I find it best not to speak.",options:["yes","in between","no"]},
  {id:167,text:"In education, it is more important to:",options:["give the child enough affection","in between","have the child learn desirable habits and attitudes"]},
  {id:168,text:"People regard me as a solid, undisturbed person, unmoved by ups and downs in circumstances.",options:["yes","in between","no"]},
  {id:169,text:"I think society should let reason lead it to new customs and throw aside old habits or mere traditions.",options:["yes","in between","no"]},
  {id:170,text:"I think it is more important in the modern world to solve:",options:["the question of moral purpose","uncertain","the political difficulties"]},
  {id:171,text:"I learn better by:",options:["reading a well-written book","in between","joining a group discussion"]},
  {id:172,text:"I like to go my own way instead of acting on approved rules.",options:["true","uncertain","false"]},
  {id:173,text:"I like to wait till I am sure that what I am saying is correct, before I put forth an argument.",options:["always","generally","only if it's practicable"]},
  {id:174,text:'Small things sometimes "get on my nerves" unbearably, though I realize they are trivial.',options:["yes","in between","no"]},
  {id:175,text:"I don't often say things on the spur of the moment that I greatly regret.",options:["true","uncertain","false"]},
  {id:176,text:"If asked to work with a charity drive, I would:",options:["accept","uncertain","politely say I'm too busy"]},
  {id:177,text:"Which of the following words does not belong with the others?",options:["wide","zigzag","straight"]},
  {id:178,text:'"Soon" is to "never" as "near" is to:',options:["nowhere","far","away"]},
  {id:179,text:"If I make an awkward social mistake, I can soon forget it.",options:["yes","in between","no"]},
  {id:180,text:'I am known as an "idea man" who almost always puts forward some ideas on a problem.',options:["yes","in between","no"]},
  {id:181,text:"I think I am better at showing:",options:["nerve in meeting challenges","uncertain","tolerance of other people's wishes"]},
  {id:182,text:"I am considered a very enthusiastic person.",options:["yes","in between","no"]},
  {id:183,text:"I like a job that offers change, variety, and travel, even if it involves some danger.",options:["yes","in between","no"]},
  {id:184,text:"I am a fairly strict person, insisting on always doing things as correctly as possible.",options:["true","in between","false"]},
  {id:185,text:"I enjoy work that requires conscientious, exacting skills.",options:["yes","in between","no"]},
  {id:186,text:"I'm the energetic type who keeps busy.",options:["yes","uncertain","no"]},
  {id:187,text:"I am sure there are no questions that I have skipped or failed to answer properly.",options:["yes","uncertain","no"]},
];
